
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Nav from "../components/nav";
import Footer from "../components/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <>
          <Nav />
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
